"""empty message

Revision ID: d6480da3b4cc
Revises: 5b70ec78aee7
Create Date: 2022-04-24 13:31:06.986576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6480da3b4cc'
down_revision = '5b70ec78aee7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('visitors', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('visitors', 'd_zodiac',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint('visitors_email_key', 'visitors', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('visitors_email_key', 'visitors', ['email'])
    op.alter_column('visitors', 'd_zodiac',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('visitors', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
